variables:
  Horton.FrameworkRoot: $(Build.SourcesDirectory)

command: ["/bin/sh","-c"]
args: ["python --version && python3 --version"]

jobs:
- template: vsts/templates/jobs-build-docker-image.yaml
  parameters:
    langauge: 'pythonv2'
    repo: 'Azure/iot-sdks-e2e-fx'
    commit: 'master'
    forced_image: ''
    job_tag: 'linux'
    variant: 'linux'
    repo_address: $(IOTHUB-E2E-REPO-ADDRESS)
    repo_user: $(IOTHUB-E2E-REPO-USER)
    repo_password: $(IOTHUB-E2E-REPO-PASSWORD)

